CREATE ROLE TESTE;
GRANT CREATE ORGANIZATION LISTING ON ACCOUNT TO ROLE TESTE;

GRANT CREATE ORGANIZATION LISTING ON ACCOUNT TO ROLE TESTE;

GRANT ROLE TESTE TO ROLE ACCOUNTADMIN;

drop role TESTE;
 select current_version();
 
