CREATE DATABASE IF NOT EXISTS DB_DEVOPS_{{ AMBIENTE }};

CREATE SCHEMA IF NOT EXISTS DB_DEVOPS_{{ AMBIENTE }}.BRONZE;

CREATE SCHEMA IF NOT EXISTS DB_DEVOPS_{{ AMBIENTE }}.SILVER;

CREATE SCHEMA IF NOT EXISTS DB_DEVOPS_{{ AMBIENTE }}.GOLD;


