CREATE DATABASE IF NOT EXISTS DB_DEVOPS_{{ AMBIENTE }};

CREATE SCHEMA IF NOT EXISTS {{ AMBIENTE }}.BRONZE;

CREATE SCHEMA IF NOT EXISTS {{ AMBIENTE }}.SILVER;

CREATE SCHEMA IF NOT EXISTS {{ AMBIENTE }}.GOLD;


