USE DATABASE DB_DEVOPS_{{ AMBIENTE }};

USE SCHEMA PUBLIC;


--CONTATOS
CREATE CONTACT IF NOT EXISTS PUBLIC.DEPT_RH EMAIL_DISTRIBUTION_LIST = 'fd_dl@example.com';
CREATE CONTACT IF NOT EXISTS PUBLIC.DBAS USERS = ('dpiroto');

--TAGS
CREATE TAG IF NOT EXISTS PUBLIC.CENTRO_CUSTO ALLOWED_VALUES 'FINANCEIRO','MARKETING','RH' ;