USE DATABASE DB_DEVOPS_{{ AMBIENTE }};

CREATE OR ALTER TABLE BRONZE.CLIENTES(
    ID INT IDENTITY, 
    NOME VARCHAR,
    DataNascimento timestamp, 
    ESTADO VARCHAR,
    
    ARQUIVO_INGESTAO STRING,
    LINHA_ARQUIVO INT,
    DATA_INGESTAO TIMESTAMP
)
COMMENT = 'Tabela Usada para marzenar dados de clientes da empresa'
;

--Tags
ALTER TABLE BRONZE.CLIENTES SET TAG PUBLIC.CENTRO_CUSTO = 'RH';

--Contacts
ALTER TABLE BRONZE.CLIENTES SET CONTACT STEWARD = PUBLIC.DBAS;
ALTER TABLE BRONZE.CLIENTES SET CONTACT Steward = PUBLIC.DEPT_RH;


--Data Quality
ALTER TABLE BRONZE.CLIENTES SET DATA_METRIC_SCHEDULE = 'TRIGGER_ON_CHANGES';

ALTER TABLE BRONZE.CLIENTES ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.ROW_COUNT ON ();

ALTER TABLE BRONZE.CLIENTES ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (NOME) EXPECTATION my_exp ( VALUE < 0);
ALTER TABLE BRONZE.CLIENTES ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (DataNascimento) EXPECTATION my_exp ( VALUE < 0);
ALTER TABLE BRONZE.CLIENTES ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (ESTADO) EXPECTATION my_exp ( VALUE < 0);


